version: 0.0
os: linux
files:
  - source: /sites/SkillTracker.WebAPI/app
    destination: /var/www/
  - source: /sites/SkillTracker.WebAPI/deploy-scripts/webapi.service
    destination: /etc/systemd/system
hooks:
  BeforeInstall:
    - location: /sites/SkillTracker.WebAPI/deploy-scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /sites/SkillTracker.WebAPI/deploy-scripts/stop_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /sites/SkillTracker.WebAPI/deploy-scripts/start_app.sh
      timeout: 300
      runas: root